name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: configure all
      run: cmake -DWITH_examples=ON -DWITH_tests=ON -DWITH_demos=ON .
    
    - name: Rich Code Nav Indexer
      uses: microsoft/RichCodeNavIndexer@v0.1.16
      with:
        repo-token: ${{ github.token }}
      languages: cpp

