name: CMake Testsuite

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: configure all
      run: cmake -DWITH_examples=ON -DWITH_tests=ON -DWITH_demos=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON . 
    
    - name: Rich Code Nav
    - uses: microsoft/RichCodeNavIndexer@v0.1.16
      with:
        repo-token: ${{ github.token }}
        languages: cpp
      
  cmake-testsuite:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0
    - name: install dependencies
      run: sudo apt-get install -y libboost-dev libboost-program-options-dev libmpfr-dev libeigen3-dev
    - name: configure all
      run: |
        set -e
        mkdir build && cd build && CXX=clang++ cmake -DWITH_examples=ON -DWITH_tests=ON -DWITH_demos=ON -DBUILD_TESTING=ON ..
        ctest -L Installation -j $(getconf _NPROCESSORS_ONLN)

  cmake-testsuite-with-qt5:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0
    - name: install dependencies
      run: sudo bash -e .github/install.sh
    - name: configure all
      run: |
        set -e
        mkdir build && cd build && CXX=clang++ cmake -DWITH_examples=ON -DWITH_tests=ON -DWITH_demos=ON -DBUILD_TESTING=ON ..
        ctest -L Installation -j $(getconf _NPROCESSORS_ONLN)
      
